### ISSUE TITLE
Use Result instead of panic

### ISSUE THREAD

**Issue by peterdk** [residua/mutf8#1]
Hi, I am using your library to parse some strings. Works great, but to be resilient, I would like to catch errors instead of having a panic.
I am new to Rust, to be honest, but catching global panics seems to be a bit of a no go.

I was wondering why you didn't return a Result instead of panicing?

**Comment by seancroach** [comment]
Hello! Sorry for the untimely response.

I choose to panic for two reasons. The first is section 9.3 of the Rust Book, found [here](https://doc.rust-lang.org/book/ch09-03-to-panic-or-not-to-panic.html). Like CESU-8, MUTF-8 is an internal-only format, so malformed data is almost always a security vulnerability or a bug. It's genuinely a by-design choice. The second, of course, is that *I* didn't need it. As you can guess, the first is much more important than the second.

If you can drum up a real-life use case that does demand the handling of invalid data between internal systems (which I really doubt), I'll make a newer version that works on results. Remember, though, it should be treated like the trivial `Vec::remove`, where panicking prevails.

**Comment by peterdk** [comment]
Thanks for your comment. My usecase is in parsing Android's .dex files, which contains executable code and JVM class information. Goal of the parsing is (besides other info) to return all classnames. The strings that are present in .dex files are MUTF-8. I do all kinds of verification checks that the dex file is indeed proper, but since it reads .dex files out in the wild, there could be issues with them. One of them could be a malformed MUTF-8 string. It's probably not occurring very often, but it's just one of the checks I need to do. Parse MUTF-8 string from dex file (for a classname for example). If invalid, return that the dex file is corrupt, and continue with the next file.
Panic! here seems like overkill. I just want to know if the dex is valid, and then continue with the next one in case it's not.

**Comment by seancroach** [comment]
Sounds good! I'll add that to my weekend projects, then.

**Comment by seancroach** [comment]
Great! Instead of panicking, `mutf8` (as well as the `cesu8` crate) reports errors as of version `1.0.0`. Thanks for your feedback and for helping to improve both of these crates.
